documents = "data/documents.json"
entities = "data/entities.json"

[database]
host = "dmz-dbcluster.dmz.dsmz.de"
database = "brenda_conn"
backend = "mysql"

[sources]
bacteria = "data/bacteria.txt"
lpsn = "data/lpsn_gss_2024-11-19.csv"

