documents = "src/brenda_references/data/documents.json"
entities = "src/brenda_references/data/entities.json"

[database]
host = "dmz-dbcluster.dmz.dsmz.de"
database = "brenda_conn"
backend = "mysql"

[sources]
bacteria = "src/brenda_references/data/bacteria.txt"
lpsn = "src/brenda_references/data/lpsn_gss_2025-04-07.csv"

